name: smart_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_inappwebview: ^6.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  iconly: ^1.0.1
  icons_plus: ^5.0.0
  image_picker: ^1.0.7
  lottie: ^3.1.0
  path: ^1.9.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

